import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

const THEME_GREEN = '#43A047';

const styles = StyleSheet.create({
  searchBar: {
    backgroundColor: '#F2F2F7',
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    color: '#222',
  },
  bookmarkBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 16,
    padding: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  modalImage: {
    width: '100%',
    height: 160,
    borderRadius: 14,
    marginBottom: 14,
    resizeMode: 'cover',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 6,
    textAlign: 'center',
  },
  modalMeta: {
    fontSize: 14,
    color: '#888',
    marginBottom: 10,
  },
  modalBody: {
    fontSize: 16,
    color: '#333',
    marginBottom: 18,
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalActionBtn: {
    flex: 1,
    alignItems: 'center',
    padding: 8,
  },
  modalActionText: {
    fontSize: 13,
    color: THEME_GREEN,
    marginTop: 2,
  },
  topNewsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginBottom: 0,
    marginTop: 0,
  },
  seeAllBtn: {
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 12,
  },
  seeAllText: {
    color: '#007AFF',
    fontWeight: '600',
    fontSize: 15,
  },
  divider: {
    height: 1.5,
    backgroundColor: '#e5e5e5',
    marginHorizontal: 16,
    marginVertical: 0,
    borderRadius: 1,
  },
  verticalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 16,
    marginBottom: 10,
  },
  badge: {
    backgroundColor: '#FF3B30',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginLeft: 10,
    alignSelf: 'flex-start',
  },
  badgeText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 11,
    letterSpacing: 1,
  },
  topNewsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: THEME_GREEN,
    backgroundColor: '#E8F5E9', // light green
    marginLeft: 16,
    marginBottom: 0,
    marginTop: 0,
    letterSpacing: 0.2,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginBottom: 12,
    marginTop: 0,
  },
  bellButton: {
    padding: 6,
    borderRadius: 20,
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 40,
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    marginLeft: 0,
    marginBottom: 0,
  },
  horizontalScroll: {
    minHeight: 240,
    maxHeight: 260,
    marginBottom: 18,
    paddingLeft: 16,
    marginTop: 0,
  },
  cardHorizontal: {
    width: width * 0.7,
    marginRight: 18,
    backgroundColor: '#fff',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    overflow: 'hidden',
    minHeight: 150,
    maxHeight: 200,
  },
  cardImageHorizontal: {
    width: '100%',
    height: 90,
    resizeMode: 'cover',
  },
  cardContentHorizontal: {
    padding: 10,
  },
  cardTitleHorizontal: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
    marginBottom: 4,
  },
  cardSubtitleHorizontal: {
    fontSize: 14,
    color: '#888',
  },
  verticalSectionBg: {
    backgroundColor: '#F6F7F9',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 6,
    flex: 1,
    marginTop: 0,
  },
  verticalSectionHeader: {
    fontSize: 20,
    fontWeight: '700',
    color: THEME_GREEN,
    backgroundColor: '#E8F5E9', // light green
    marginLeft: 16,
    marginBottom: 10,
    letterSpacing: 0.2,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  verticalScroll: {
    flex: 1,
    marginHorizontal: 0,
    paddingHorizontal: 16,
  },
  cardVertical: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 22,
    backgroundColor: '#fff',
    borderRadius: 22,
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    padding: 16,
    overflow: 'hidden',
    minHeight: 110,
  },
  cardVerticalFirst: {
    marginTop: 2,
  },
  cardImageVertical: {
    width: 90,
    height: 90,
    borderRadius: 16,
    marginRight: 18,
    resizeMode: 'cover',
    backgroundColor: '#e0e0e0',
  },
  cardContentVertical: {
    flex: 1,
    justifyContent: 'center',
  },
  cardTitleVertical: {
    fontSize: 17,
    fontWeight: '700',
    color: '#222',
    marginBottom: 3,
  },
  cardSubtitleVertical: {
    fontSize: 13,
    color: '#888',
  },
});

export default styles;
